// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateTSP(arg1) {
  return window['go']['main']['App']['CalculateTSP'](arg1);
}

export function LoadScenarioFile(arg1) {
  return window['go']['main']['App']['LoadScenarioFile'](arg1);
}

export function OpenFileAndLoadScenario() {
  return window['go']['main']['App']['OpenFileAndLoadScenario']();
}

export function PerformCSRSCalculation(arg1) {
  return window['go']['main']['App']['PerformCSRSCalculation'](arg1);
}

export function PerformFERSCalculation(arg1) {
  return window['go']['main']['App']['PerformFERSCalculation'](arg1);
}

export function PerformRetirementCalculation(arg1) {
  return window['go']['main']['App']['PerformRetirementCalculation'](arg1);
}

export function SaveScenarioFile(arg1, arg2) {
  return window['go']['main']['App']['SaveScenarioFile'](arg1, arg2);
}

export function SaveScenarioWithDialog(arg1) {
  return window['go']['main']['App']['SaveScenarioWithDialog'](arg1);
}
