// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scenario} from '../models';
import {models} from '../models';

export function CalculateTSP(arg1:scenario.ScenarioVariant):Promise<models.TSPCalculationResult>;

export function LoadScenarioFile(arg1:string):Promise<scenario.FerexFile>;

export function OpenFileAndLoadScenario():Promise<scenario.FerexFile>;

export function PerformCSRSCalculation(arg1:models.CSRSCalculationInput):Promise<models.CSRSCalculationResult>;

export function PerformFERSCalculation(arg1:models.FERSCalculationInput):Promise<models.FERSCalculationResult>;

export function PerformRetirementCalculation(arg1:models.RetirementCalculationInput):Promise<models.RetirementCalculationResult>;

export function SaveScenarioFile(arg1:string,arg2:scenario.FerexFile):Promise<void>;

export function SaveScenarioWithDialog(arg1:scenario.FerexFile):Promise<void>;
