// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateCOLAAdjustment(arg1) {
  return window['go']['main']['App']['CalculateCOLAAdjustment'](arg1);
}

export function CalculatePension(arg1) {
  return window['go']['main']['App']['CalculatePension'](arg1);
}

export function CalculateRetirementProjection(arg1) {
  return window['go']['main']['App']['CalculateRetirementProjection'](arg1);
}

export function CalculateSocialSecurity(arg1) {
  return window['go']['main']['App']['CalculateSocialSecurity'](arg1);
}

export function CalculateTSPProjection(arg1) {
  return window['go']['main']['App']['CalculateTSPProjection'](arg1);
}

export function CalculateTaxLiability(arg1) {
  return window['go']['main']['App']['CalculateTaxLiability'](arg1);
}

export function GetSavedScenarios() {
  return window['go']['main']['App']['GetSavedScenarios']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadScenarios(arg1) {
  return window['go']['main']['App']['LoadScenarios'](arg1);
}

export function SaveScenarios(arg1) {
  return window['go']['main']['App']['SaveScenarios'](arg1);
}
