// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CalculatePension(arg1:main.PensionInput):Promise<main.PensionResult>;

export function Greet(arg1:string):Promise<string>;
