// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CalculateCOLAAdjustment(arg1:main.COLAInput):Promise<main.COLAResult>;

export function CalculatePension(arg1:main.PensionInput):Promise<main.PensionResult>;

export function CalculateRetirementProjection(arg1:main.RetirementScenarioInput):Promise<main.RetirementProjectionResult>;

export function CalculateSocialSecurity(arg1:main.SocialSecurityInput):Promise<main.SocialSecurityResult>;

export function CalculateTSPProjection(arg1:main.TSPInput):Promise<main.TSPProjectionResult>;

export function CalculateTaxLiability(arg1:main.TaxInput):Promise<main.TaxResult>;

export function GetSavedScenarios():Promise<main.GetSavedScenariosResult>;

export function Greet(arg1:string):Promise<string>;

export function LoadScenarios(arg1:main.LoadScenarioInput):Promise<main.LoadScenarioResult>;

export function SaveScenarios(arg1:main.SaveScenarioInput):Promise<main.SaveScenarioResult>;
